'use client';
import {useCallback,useEffect,useState} from 'react';
import {ClipboardList,BriefcaseBusiness,ListChecks,ExternalLink,CalendarClock,Plus,RefreshCw,FileSpreadsheet,Inbox,Check,Settings2,RotateCcw,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {COMPANIES,TRACKED_COMPANIES,hasApplied} from '@/lib/domain.mjs';
import type {DeskData,Job} from '@/lib/types';
const date=(v:string|null|undefined)=>v?(v.length===10?v:new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})):'—';
const initial={id:'',company:'美团',title:'',url:'',location:'',employment:'',description:'',appliedAt:'',rawStatus:''};
function NoRows({title,description}:{title:string;description:string}){return <Empty className="empty-zone"><EmptyHeader><EmptyMedia variant="icon"><Inbox/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
function Choose({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o} key={o}>{o}</SelectItem>)}</SelectContent></Select>}
export default function Workspace(){
 const [data,setData]=useState<DeskData|null>(null),[error,setError]=useState(''),[auth,setAuth]=useState(false),[busy,setBusy]=useState(false),[tab,setTab]=useState('jobs');
 const [form,setForm]=useState(initial),[add,setAdd]=useState(false),[mode,setMode]=useState('投递记录'),[filter,setFilter]=useState('符合条件'),[companyFilter,setCompanyFilter]=useState('全部公司');
 const [detail,setDetail]=useState<Job|null>(null),[observe,setObserve]=useState<Job|null>(null),[observedStatus,setObservedStatus]=useState(''),[observedDate,setObservedDate]=useState(''),[checkError,setCheckError]=useState('');
 const [settings,setSettings]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch('/api/desk',{cache:'no-store'});const result=await response.json() as DeskData & {error?:string};if(!response.ok){setAuth(response.status===401);throw new Error(result.error||'加载失败');}setData(result);setError('');setAuth(false);}catch(e){setError(e instanceof Error?e.message:'加载失败');}},[]);
 useEffect(()=>{void load();},[load]);
 const act=useCallback(async(payload:unknown)=>{setBusy(true);try{const response=await fetch('/api/desk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as DeskData & {error?:string};if(!response.ok)throw new Error(result.error||'操作失败');await load();return result;}catch(e){toast.error(e instanceof Error?e.message:'操作失败');await load();return null;}finally{setBusy(false);}},[load]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_application_desk',title:'读取ApplyDesk',description:'读取已有岗位、用户决定和投递状态；不会执行投递。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('参数必须为空对象');const response=await fetch('/api/desk');const result=await response.json() as DeskData & {error?:string};if(!response.ok)throw new Error(result.error);setData(result);return {jobs:result.jobs,schedule:result.schedule};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();
 const recordSchema={type:'object',properties:{sourceRecordId:{type:'string'},title:{type:'string'},url:{type:'string'},location:{type:'string'},employment:{type:'string'},description:{type:'string'},applied:{type:'boolean',const:true},appliedAt:{type:['string','null']},rawStatus:{type:'string'}},required:['sourceRecordId','title','url','rawStatus'],additionalProperties:true};
 const tools=[{name:'sync_recruitment_source',title:'同步官网检查结果',description:'将刚从用户指定的7家已投公司官网登录页面读取的投递记录保存到当前用户看板。只导入状态，不填写或提交招聘申请。sourceRecordId使用官网记录编号；无编号时用岗位名加原始投递时间，日期未注明时传null。登录失败时state=login_required或error，不能传记录，也不能推断被拒绝。',inputSchema:{type:'object',properties:{company:{type:'string',enum:TRACKED_COMPANIES},state:{type:'string',enum:['connected','partial','login_required','error','blocked']},sourceUrl:{type:'string'},error:{type:'string'},records:{type:'array',items:recordSchema}},required:['company','state','sourceUrl'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{setBusy(true);try{const response=await fetch('/api/source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error);await load();return result;}finally{setBusy(false);}}},
 {name:'sync_feishu_records',title:'同步投递记录到飞书',description:'把当前看板的岗位与投递状态写入已授权的专用飞书电子表格，不提交招聘申请。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('参数必须为空对象');const result=await act({action:'sync'});if(!result)throw new Error('飞书同步未完成，请查看看板诊断');return result;}}];
 for(const tool of tools)Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});
 Promise.resolve(context.registerTool({name:'sync_job_search',title:'同步官网岗位检索结果',description:'保存16家已配置官网刚读取的实习岗位；公司限定在名单内，BOSS直聘不在范围。只填写官网明确给出的工作地点、实习类型和职位描述，缺失信息保持空字符串。后台按北京、日常实习和算法方向筛选；未明确类型进入待核对。state=ready 表示本次检索可读，不能把登录或访问失败当作零岗位。此工具不会进行投递。',inputSchema:{type:'object',properties:{company:{type:'string',enum:COMPANIES.map(c=>c.name)},state:{type:'string',enum:['ready','error','login_required','blocked']},sourceUrl:{type:'string'},error:{type:'string'},items:{type:'array',items:{type:'object',properties:{title:{type:'string'},url:{type:'string'},location:{type:'string'},employment:{type:'string'},description:{type:'string'}},required:['title','url'],additionalProperties:false}}},required:['company','state','sourceUrl'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{setBusy(true);try{const response=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error);await load();return result;}finally{setBusy(false);}}},{signal:lifecycle.signal})).catch(()=>{});
 return()=>lifecycle.abort();},[load,act]);
 const jobs=data?.jobs||[],applied=jobs.filter(j=>hasApplied(j)),queue=jobs.filter(j=>j.decision==='approved'&&!hasApplied(j));
 const pending=jobs.filter(j=>j.matchState==='matched'&&j.decision==='pending'&&!hasApplied(j));
 const shown=jobs.filter(j=>!hasApplied(j)&&(companyFilter==='全部公司'||j.company===companyFilter)&&(filter==='符合条件'?j.matchState==='matched'&&j.decision==='pending':filter==='待核对'?j.matchState==='review'&&j.decision==='pending':filter==='不考虑'?j.decision==='ignored':j.matchState==='excluded'&&j.decision==='pending'));
 const decide=async(job:Job,decision:string)=>{if(await act({action:'decide',id:job.id,decision}))toast.success(decision==='approved'?'已确认，进入待投递队列':decision==='ignored'?'已标记为不考虑':'已撤回决定');};
 const showObserve=(job:Job)=>{setObserve(job);setObservedStatus(job.rawStatus||'');setObservedDate(job.appliedAt?new Date(new Date(job.appliedAt).getTime()+8*3600000).toISOString().slice(0,16):'');setCheckError('');};
 const save=async(e:React.FormEvent)=>{e.preventDefault();const item={...form,id:form.id||undefined,...(mode==='投递记录'?{appliedAt:form.appliedAt?new Date(form.appliedAt+'+08:00').toISOString():null}:{appliedAt:null,rawStatus:''})};if(await act({action:'import',jobs:[item]})){setAdd(false);setForm(initial);toast.success('记录已保存');setTab(mode==='投递记录'?'applications':'jobs');}};
 const metrics=[{label:'待确认岗位',value:pending.length,Icon:Inbox},{label:'跟进中',value:applied.filter(j=>j.stage!=='已结束').length,Icon:BriefcaseBusiness},{label:'待投递',value:queue.length,Icon:ListChecks},{label:'已结束',value:applied.filter(j=>j.stage==='已结束').length,Icon:ClipboardList}];
 return <><Toaster position="top-center" richColors/><header className="mast"><div className="brand"><div className="brandmark"><ClipboardList size={23}/></div><div><strong>ApplyDesk</strong><br/><small>APPLYDESK</small></div></div><div className="actions"><span className="time">北京 · 日常实习</span><Button variant="ghost" onClick={()=>setSettings(true)} aria-label="查看筛选与接入设置" style={{color:'#dce7fa'}}><Settings2 size={19}/></Button></div></header>
 <main className="shell"><div className="intro"><div><h1>每一次投递，都有记录。</h1><p className="sub">大模型应用算法 / Agent / 业务算法 / 后训练</p></div><div className="actions"><Button variant="outline" disabled={busy} onClick={()=>void load()}><RefreshCw/>刷新记录</Button><Button disabled={!data||busy} onClick={()=>setAdd(true)}><Plus/>添加记录</Button></div></div>
 {error&&<div className="error-banner" role="alert">{error} {auth?<span>请在本机启动开发服务；公开部署需要自行接入认证。</span>:<button onClick={()=>void load()}>重试</button>}</div>}
 <section className="metrics">{metrics.map(({label,value,Icon})=><div className="metric" key={label}><div><span>{label}</span><b>{data?value:'—'}</b></div><Icon/></div>)}</section>
 <div className="notice">{data?.sources?.some(s=>s.state==='connected')?'已接入官网检查记录，状态保留官网原文。工作日 10:00 的自动任务还未启用。':'官网尚未连接，工作日 10:00 的自动任务还未启用。'}</div>
 <div className="columns"><section className="panel"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="section-nav"><TabsTrigger value="jobs">推荐岗位{pending.length>0&&` ${pending.length}`}</TabsTrigger><TabsTrigger value="applications">投递进度</TabsTrigger><TabsTrigger value="queue">投递队列{queue.length>0&&` ${queue.length}`}</TabsTrigger><TabsTrigger value="history">更新记录</TabsTrigger><TabsTrigger value="sources">官网接入</TabsTrigger></TabsList>
 <TabsContent value="jobs"><div className="toolbar"><Choose label="岗位范围" value={filter} onChange={setFilter} options={['符合条件','待核对','不考虑','不符合条件']}/><Choose label="公司筛选" value={companyFilter} onChange={setCompanyFilter} options={['全部公司',...COMPANIES.map(c=>c.name)]}/></div>{shown.length?shown.map(job=><article className="job" key={job.id}><div className="job-top"><div><h3>{job.title}</h3><div className="job-meta"><span>{job.company}</span><span>{job.location||'地点未注明'}</span><span>{job.employment||'实习类型未注明'}</span></div></div><span className="tag">{job.direction||'方向待核对'}</span></div><p className="job-text">{job.matchReason}</p><div className="job-foot"><div className="actions"><Button variant="ghost" onClick={()=>setDetail(job)}>查看详情</Button><a href={job.url} target="_blank" rel="noreferrer" className="fine">官网原文 <ExternalLink size={12} style={{display:'inline'}}/></a></div><div className="actions">{job.decision==='ignored'?<Button variant="outline" disabled={busy} onClick={()=>void decide(job,'pending')}><RotateCcw/>恢复</Button>:<><Button variant="ghost" disabled={busy} onClick={()=>void decide(job,'ignored')}>不考虑</Button><Button disabled={busy||job.matchState!=='matched'} onClick={()=>void decide(job,'approved')}><Check/>确认要投</Button></>}</div></div></article>):<NoRows title={data?'这里还没有岗位':error?'暂时无法加载记录':'正在读取记录'} description={filter==='符合条件'?'北京、日常实习、方向匹配的岗位会出现在这里，等你逐个确认。':'该分类下暂无记录。未明确说明地点或实习类型的岗位会进入待核对。'}/>}</TabsContent>
 <TabsContent value="applications">{applied.length?<Table><TableHeader><TableRow><TableHead>公司 / 岗位</TableHead><TableHead>官网状态</TableHead><TableHead>投递 / 检查时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{applied.map(job=><TableRow key={job.id}><TableCell><button className="table-title" onClick={()=>setDetail(job)}>{job.title}</button><span className="table-sub">{job.company} · {job.location||'未注明'}</span></TableCell><TableCell><span className={`status ${job.stage==='已结束'?'negative':job.stage==='Offer'?'positive':''}`}>{job.stage}</span><span className="table-sub" style={{whiteSpace:'normal'}}>{job.rawStatus||'尚未记录官网原文'}</span>{job.checkError&&<span className="table-sub" style={{color:'#b67618',whiteSpace:'normal'}}>检查异常：{job.checkError}</span>}</TableCell><TableCell><span className="fine">投递 {job.appliedAt?date(job.appliedAt):'官网未注明'}<br/>检查 {date(job.checkedAt)}</span></TableCell><TableCell><Button size="sm" variant="outline" disabled={busy} onClick={()=>showObserve(job)}>更新状态</Button></TableCell></TableRow>)}</TableBody></Table>:<NoRows title="还没有投递记录" description="连接官网后同步已有投递。也可以先添加记录，保留官网状态原文。"/>}</TabsContent>
 <TabsContent value="queue"><div className="toolbar"><span className="fine">已确认 {queue.length} 个岗位 · 等待简历匹配和官网提交功能接入</span></div>{queue.length?queue.map(job=><article className="job" key={job.id}><div className="job-top"><div><h3>{job.title}</h3><div className="job-meta">{job.company} · {job.direction}</div></div><span className="tag">待投递</span></div><div className="job-foot" style={{marginTop:20}}><a href={job.url} target="_blank" rel="noreferrer" className="fine">查看官网岗位</a><div className="actions"><Button variant="ghost" disabled={busy} onClick={()=>void decide(job,'pending')}>撤回确认</Button><Button variant="outline" disabled={busy} onClick={()=>showObserve(job)}>补记已完成的投递</Button></div></div></article>):<NoRows title="确认后，岗位会进入这里" description="确认要投只代表你的决定。官网提交成功后，岗位才会进入投递进度。"/>}</TabsContent>
 <TabsContent value="history">{data?.events.length?data.events.map(item=><div className="history" key={item.id}>{item.message}<time>{date(item.createdAt)}</time></div>):<NoRows title="尚无更新记录" description="岗位决定、投递状态变化和检查异常都会保留记录。"/>}</TabsContent>
 <TabsContent value="sources"><div className="toolbar"><span className="fine">16 家检索官网 · 投递跟踪范围见项目配置 · BOSS 直聘已排除</span></div><Table><TableHeader><TableRow><TableHead>公司</TableHead><TableHead>职位检索</TableHead><TableHead>投递记录</TableHead><TableHead>最近检查</TableHead></TableRow></TableHeader><TableBody>{COMPANIES.map(c=>{const tracked=TRACKED_COMPANIES.includes(c.name),source=data?.sources?.find(x=>x.company===c.name),search=data?.searches?.find(x=>x.company===c.name);const labels:Record<string,string>={ready:'可检索',connected:'可读取',partial:'部分读取',login_required:'需要登录',blocked:'访问受限',error:'检查异常'};return <TableRow key={c.name}><TableCell><a href={c.url} target="_blank" rel="noreferrer">{c.name}</a></TableCell><TableCell><span className="status">{search?labels[search.state]:'未验证'}</span><span className="table-sub" style={{whiteSpace:'normal'}}>{search?.error||(search?.state==='ready'?`本次收录 ${search.itemCount} 条`:'')}</span></TableCell><TableCell><span className="status">{tracked?(source?labels[source.state]:'未验证'):'仅检索岗位'}</span><span className="table-sub" style={{whiteSpace:'normal'}}>{tracked?(source?.error||(source?.state==='connected'?`${source.recordCount} 条投递记录`:'')):''}</span></TableCell><TableCell><span className="fine">{date(source?.checkedAt||search?.checkedAt)}</span></TableCell></TableRow>;})}</TableBody></Table></TabsContent></Tabs></section><aside className="aside"><section className="panel"><div className="panel-head"><h2>招聘官网</h2><span className="tag">{data?.sources?.filter(s=>TRACKED_COMPANIES.includes(s.company)&&s.state==='connected').length||0} / {TRACKED_COMPANIES.length} 投递可读</span></div><div className="panel-body sources-scroll">{COMPANIES.map(c=><div className="company" key={c.name}><span className="company-icon" style={{background:c.color}}>{c.letter}</span><div className="company-text"><div className="company-name">{c.name}</div><div className="company-state">{(()=>{if(!TRACKED_COMPANIES.includes(c.name))return '仅检索岗位，无需登录';const source=data?.sources?.find(s=>s.company===c.name);return source?source.state==='connected'?`已接通 · ${source.recordCount} 条记录`:source.error||'需要重新登录':'尚未验证连接';})()}</div></div><a href={c.url} target="_blank" rel="noreferrer" aria-label={`打开${c.name}招聘官网`}><ExternalLink size={15}/></a></div>)}</div></section>
 <section className="panel"><div className="panel-head"><h2>每日检查</h2><CalendarClock size={18}/></div><div className="panel-body"><div className="connection-line"><span>周一至周五</span><span className="tag">待启用</span></div><div className="schedule-time">10:00 <small style={{fontSize:13,fontWeight:400}}>北京时间</small></div><p className="schedule-note">接通官网后启用定时检查</p><div className="pending-step"><b>1</b>检查已投岗位状态</div><div className="pending-step"><b>2</b>筛选新岗位，交给你确认</div><div className="pending-step"><b>3</b>更新飞书投递记录</div></div></section>
 <section className="panel"><div className="panel-head"><h2>飞书表格</h2><FileSpreadsheet size={18}/></div><div className="panel-body"><div className="connection-line"><span>{data?.feishu.configured?'已配置飞书应用':'等待授权接入'}</span></div><p className="fine">公司、岗位、投递时间、官网状态与最近检查时间。</p>{data?.feishu.configured?<Button variant="outline" disabled={busy} onClick={async()=>{if(await act({action:'sync'}))toast.success('已同步到飞书表格');}}>{data.feishu.sheetUrl?'同步记录':'创建并同步表格'}</Button>:<Button variant="outline" onClick={()=>setSettings(true)}>查看接入说明</Button>}{data?.feishu.sheetUrl&&<p className="sync-note"><a href={data.feishu.sheetUrl} target="_blank" rel="noreferrer">打开飞书表格 <ExternalLink size={12} style={{display:'inline'}}/></a></p>}{data?.feishu.syncedAt&&<p className="sync-note">上次同步 {date(data.feishu.syncedAt)}</p>}{data?.feishu.syncError&&<p className="sync-note" style={{color:'#ac354b'}}>{data.feishu.syncError}</p>}</div></section></aside></div><footer className="footer"><span>仅北京 · 日常实习 · 逐个确认后投递</span><span>官网状态保留原文，不根据等待时长推断拒绝</span></footer></main>
 <Dialog open={add} onOpenChange={setAdd}><DialogContent style={{maxWidth:620,maxHeight:'90vh',overflowY:'auto'}}><DialogHeader><DialogTitle>添加记录</DialogTitle><DialogDescription>按官网原文填写。缺少地点或实习类型时，岗位将进入待核对。</DialogDescription></DialogHeader><form onSubmit={e=>void save(e)} className="form-grid"><label className="field">记录类型<Choose label="记录类型" value={mode} onChange={setMode} options={['投递记录','候选岗位']}/></label><label className="field">公司<Choose label="公司" value={form.company} onChange={v=>setForm({...form,company:v})} options={COMPANIES.map(c=>c.name)}/></label>{[['title','岗位名称'],['url','官网岗位链接'],['location','工作地点'],['employment','招聘类型']].map(([key,label])=><label className={`field ${key==='url'?'span-all':''}`} key={key}>{label}<input name={key} type={key==='url'?'url':'text'} required={key==='title'||key==='url'} maxLength={key==='url'?2000:200} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={key==='employment'?'例如：日常实习':undefined}/></label>)}<label className="field span-all">岗位描述<textarea value={form.description} maxLength={16000} onChange={e=>setForm({...form,description:e.target.value})}/></label>{mode==='投递记录'&&<><label className="field">实际投递时间（北京时间）<input type="datetime-local" required={!form.id} value={form.appliedAt} onChange={e=>setForm({...form,appliedAt:e.target.value})}/></label><label className="field">官网状态原文<input value={form.rawStatus} maxLength={500} onChange={e=>setForm({...form,rawStatus:e.target.value})}/></label></>}<div className="actions span-all" style={{justifyContent:'flex-end'}}><Button type="button" variant="ghost" onClick={()=>setAdd(false)}>取消</Button><Button type="submit" disabled={busy}>{busy?'正在保存':'保存记录'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent><DialogHeader><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>{detail?.company} · {detail?.location||'地点未注明'} · {detail?.employment||'实习类型未注明'}</DialogDescription></DialogHeader><span className="tag">{detail?.matchReason}</span><Button variant="outline" onClick={()=>{if(!detail)return;setForm({id:detail.id,company:detail.company,title:detail.title,url:detail.url,location:detail.location,employment:detail.employment,description:detail.description,appliedAt:detail.appliedAt&&detail.appliedAt.length>10?new Date(new Date(detail.appliedAt!).getTime()+8*3600000).toISOString().slice(0,16):"",rawStatus:detail.rawStatus||""});setMode(hasApplied(detail)?"投递记录":"候选岗位");setDetail(null);setAdd(true);}}>编辑岗位资料</Button><div className="detail-pre">{detail?.description||'尚未录入岗位描述'}</div>{detail&&<a href={detail.url} target="_blank" rel="noreferrer" className="fine">查看官网原文</a>}</DialogContent></Dialog>
 <Dialog open={!!observe} onOpenChange={v=>!v&&setObserve(null)}><DialogContent><DialogHeader><DialogTitle>核对投递状态</DialogTitle><DialogDescription>{observe?.company} · {observe?.title}</DialogDescription></DialogHeader><form className="form-grid" onSubmit={async e=>{e.preventDefault();const result=await act({action:'observe',id:observe?.id,...(checkError?{checkError}:{rawStatus:observedStatus,appliedAt:observedDate?new Date(observedDate+'+08:00').toISOString():undefined})});if(result){setObserve(null);toast.success(checkError?'已记录异常，保留原状态':'状态已更新');}}}><label className="field span-all">官网状态原文<input value={observedStatus} required={!checkError} maxLength={500} disabled={!!checkError} onChange={e=>setObservedStatus(e.target.value)}/></label>{!(observe&&hasApplied(observe))&&<label className="field span-all">实际投递时间（北京时间）<input type="datetime-local" value={observedDate} required={!checkError} disabled={!!checkError} onChange={e=>setObservedDate(e.target.value)}/></label>}<label className="field span-all">若无法检查，记录原因<input placeholder="例如：登录过期、页面无法打开" value={checkError} maxLength={500} onChange={e=>setCheckError(e.target.value)}/></label><p className="fine span-all">检查失败会保留上一次官网状态及成功检查时间。</p><Button className="span-all" disabled={busy} type="submit">保存检查结果</Button></form></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent style={{maxWidth:580,maxHeight:'90vh',overflowY:'auto'}}><DialogHeader><DialogTitle>筛选与接入</DialogTitle><DialogDescription>按已经确认的要求执行。</DialogDescription></DialogHeader><div className="settings"><div className="settings-row"><h3>筛选条件</h3><div className="actions"><span className="tag">北京</span><span className="tag">日常实习</span></div><p className="fine">大模型应用算法、Agent、业务算法、后训练。到岗时间、每周天数和实习时长不作为筛选条件。</p></div><div className="settings-row"><h3>官网与每日检查</h3><p className="fine">通过你授权的浏览器代理读取官网账户。{data?.sources?.some(s=>s.state==='connected')?'已导入官网观察记录，逐站状态见“官网接入”。定时检查尚未开启。':'当前尚未连接浏览器，也尚未开启自动检查。'}目标时间为周一至周五 10:00（北京时间）。</p></div><div className="settings-row"><h3>飞书表格</h3><p className="fine">需要接入有电子表格读写权限的飞书应用。接入后，本工具创建专用投递表格；不会覆盖你的其他表格。{data?.feishu.configured?"应用凭据已配置，可在看板创建或同步专用表格。":"当前尚未完成授权。"}</p></div><div><h3>简历与自动投递</h3><p className="fine">简历版本匹配暂缓。确认后的岗位会保存在队列中，自动填写与提交尚未接入。</p></div></div></DialogContent></Dialog>
 </>;
}
