'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from './ui/select';
import type {Job} from '@/lib/types';
import {toast} from 'sonner';

type Resume={id:string;label:string;fileName:string;sha256:string;size:number;directions:string[]};
type Task={id:string;state:string;job:Job;resumeName:string;reason?:string;receipt?:{url:string;text:string};updatedAt:string};
type Result={resumes:Resume[];tasks:Task[];projectPath:string};
const states:Record<string,string>={queued:'待交给 Codex',filling:'填写中',needs_input:'需要处理',submitting:'正在提交',unknown:'结果待核实',verified:'回执已保存，待同步记录',submitted:'已投递',cancelled:'已取消'};
export default function ApplicationsPanel({jobs,onRefresh}:{jobs:Job[];onRefresh:()=>Promise<void>}){
 const [data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[label,setLabel]=useState(''),[direction,setDirection]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<Job|null>(null),[resumeId,setResumeId]=useState(''),[confirmed,setConfirmed]=useState(false),[handoff,setHandoff]=useState<{prompt:string;codexUrl:string}|null>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/local-applications',{cache:'no-store'});if(!r.ok)throw new Error('简历和投递功能需要通过本机启动器运行');const d=await r.json() as Result;setData(d);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer);},[load]);
 const action=async(payload:unknown)=>{const r=await fetch('/api/local-applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as {error?:string;prompt:string;codexUrl:string};if(!r.ok)throw new Error(result.error);await load();await onRefresh();return result;};
 const queue=jobs.filter(j=>j.decision==='approved'&&!j.applied&&!j.appliedAt);
 return <div className="applications-panel">{error&&<p role="alert" className="error-banner">{error}</p>}<section className="resume-box"><h3>我的简历版本</h3><p className="fine">PDF / DOCX，最多 8 MB。文件保存在本机私有目录；只有确认具体岗位后才交给 Codex 上传给招聘方。</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();if(!file)return;setBusy(true);try{const form=new FormData();form.set('file',file);form.set('label',label||file.name);form.set('directions',direction);const r=await fetch('/api/local-resumes',{method:'POST',body:form});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error);await load();toast.success('简历版本已保存');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><label className="field">版本名称<input value={label} maxLength={100} placeholder="例如 Agent 秋招版" onChange={e=>setLabel(e.target.value)}/></label><label className="field">适用方向（逗号分隔，可选）<input value={direction} placeholder="Agent,后训练" onChange={e=>setDirection(e.target.value)}/></label><label className="field span-all">选择简历<input type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button type="submit" disabled={!file||busy||!data}>保存简历版本</Button></form><div className="resume-list">{data?.resumes.map(r=><div key={r.id}><strong>{r.label}</strong><span className="fine"> {r.fileName} · {Math.ceil(r.size/1024)} KB · 版本 {r.sha256.slice(0,10)}</span></div>)}</div></section>
 <section><h3>一键投递 · 交给 Codex 执行</h3><p className="fine">可直接打开官网自行投递；或选择简历交给 Codex 填写、提交并核验回执。打开官网不会自动记为已投递。</p>{!queue.length&&<p className="fine">暂无已确认的待投岗位。</p>}{queue.map(job=><div className="apply-job" key={job.id}><div><strong>{job.title}</strong><p className="fine">{job.company} · {job.location} · {job.employment}</p></div><div className="actions"><Button asChild variant="outline"><a href={job.url} target="_blank" rel="noreferrer">{data?.tasks.some(t=>t.job.id===job.id&&t.state!=='cancelled')?'打开官网核实':'官网自行投递'}</a></Button><Button disabled={!data?.resumes.length||data.tasks.some(t=>t.job.id===job.id&&t.state!=='cancelled')} onClick={()=>{setSelected(job);setResumeId(data?.resumes.find(r=>r.directions.some(d=>d.toLowerCase()===job.direction.toLowerCase()))?.id||data?.resumes[0]?.id||'');setConfirmed(false);setHandoff(null);}}>交给 Codex 投递</Button></div></div>)}</section>
 <section><h3>投递执行记录</h3>{data?.tasks.map(task=><div className="apply-job" key={task.id}><div><strong>{task.job.company} · {task.job.title}</strong><p className="fine">{task.resumeName} · {states[task.state]||task.state}</p>{task.reason&&<p className="fine">{task.reason}</p>}{task.receipt&&<a href={task.receipt.url} target="_blank" rel="noreferrer">查看官网回执页面</a>}</div><div className="actions">{['queued','needs_input'].includes(task.state)&&<Button variant="outline" onClick={()=>{const prompt=`按 docs/APPLY.md 继续投递任务 ${task.id}，先读取当前状态和授权，使用指定简历与浏览器；不要重复提交。`;setHandoff({prompt,codexUrl:'codex://new?'+new URLSearchParams({path:data!.projectPath,prompt}).toString()});}}>交给 Codex</Button>}{['queued','filling','needs_input'].includes(task.state)&&<Button variant="ghost" onClick={async()=>{try{await action({action:'cancel',id:task.id});}catch(e){toast.error((e as Error).message);}}}>取消任务</Button>}{task.state==='verified'&&<Button variant="outline" onClick={async()=>{try{await action({action:'sync',id:task.id});}catch(e){toast.error((e as Error).message);}}}>同步记录</Button>}</div></div>)}</section>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent><DialogHeader><DialogTitle>确认投递这个岗位</DialogTitle><DialogDescription>{selected?.company} · {selected?.title}</DialogDescription></DialogHeader><p className="fine">{selected?.location} · {selected?.employment}</p><label className="field">使用的简历<Select value={resumeId} onValueChange={setResumeId}><SelectTrigger aria-label="投递简历版本"><SelectValue/></SelectTrigger><SelectContent>{data?.resumes.map(r=><SelectItem key={r.id} value={r.id}>{r.label} · {r.fileName}</SelectItem>)}</SelectContent></Select></label><label className="check-label wrap"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我同意向该岗位招聘方发送这份简历并提交申请</label><p className="fine">授权只针对当前岗位和所选版本。缺少信息、验证码或网站协议需要处理时会暂停；提交结果不明时不会自动重投。</p><Button disabled={!confirmed||!resumeId||busy} onClick={async()=>{setBusy(true);try{const result=await action({action:'enqueue',jobId:selected?.id,resumeId,confirmed:true});setHandoff(result);setSelected(null);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>确认并创建投递任务</Button></DialogContent></Dialog>
 {handoff&&<section className="handoff-box"><h3>在 Codex 中执行</h3><p className="fine">下面的链接只打开预填指令，不会自行发送。发送后，Codex 才开始此任务。</p><div className="actions"><Button asChild><a href={handoff.codexUrl}>打开 Codex 执行投递</a></Button><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(handoff.prompt);toast.success('已复制');}catch{toast.info('请复制下方指令');}}}>复制指令</Button></div><textarea readOnly rows={6} value={handoff.prompt} aria-label="投递执行指令" onFocus={e=>e.target.select()}/></section>}
 </div>;
}
