'use client';
import {useEffect,useState} from 'react';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from './ui/select';
import {RECRUITMENT_TYPES} from '@/lib/recruitment.mjs';
import {assistantPrompt} from '@/lib/assistant-prompts';
import type {Preferences} from '@/lib/preferences';
import type {DeskData} from '@/lib/types';
import {toast} from 'sonner';

export function CodexActions({data,onRefresh}:{data:DeskData;onRefresh:()=>Promise<void>}){
 const [prompt,setPrompt]=useState(''),[origin,setOrigin]=useState('');useEffect(()=>setOrigin(window.location.origin),[]);
 const copy=async(mode:'check'|'schedule')=>{const text=assistantPrompt(origin,mode);setPrompt(text);try{await navigator.clipboard.writeText(text);toast.success('已复制，请粘贴到打开此项目的 Codex 对话');}catch{toast.info('请从下方文本框复制指令');}};
 return <div className="codex-actions"><div className="setup-status"><span>{data.onboarding.agentSeenAt?'Codex 已读写连接':'等待 Codex 连接'}</span><span>{data.updates.registration?'已绑定定时任务':'尚未绑定定时任务'}</span><span>飞书：{data.feishu.configured?'已配置':'可选，未配置'}</span></div><div className="actions wrap"><Button onClick={()=>void copy('check')}>复制首次／立即检查指令</Button><Button variant="outline" onClick={()=>void copy('schedule')}>复制定时更新指令</Button><Button variant="ghost" onClick={()=>void onRefresh()}>检查连接结果</Button></div><p className="fine">把指令粘贴到 Codex，让它使用你的浏览器。复制按钮不会自行启动检查，也不会自动创建定时任务。</p>{prompt&&<label className="field">给 Codex 的指令<textarea aria-label="给 Codex 的指令" readOnly value={prompt} rows={7} onFocus={e=>e.target.select()}/></label>}<p className="fine">电脑须开机联网，Codex 和浏览器连接可用。首次授权、验证码和登录由你完成；没有配置飞书也能使用全部本地记录功能。</p></div>;
}
export default function GettingStarted({data,onRefresh,open,onOpenChange}:{data:DeskData;onRefresh:()=>Promise<void>;open:boolean;onOpenChange:(v:boolean)=>void}){
 const [step,setStep]=useState(data.onboarding.configured?2:0),[p,setP]=useState<Preferences>(()=>structuredClone(data.preferences)),[targets,setTargets]=useState(data.preferences.directions.join('，')),[cities,setCities]=useState(data.onboarding.configured?data.preferences.cities.join('，'):''),[saving,setSaving]=useState(false);
 const save=async()=>{setSaving(true);try{const next={...p,directions:targets.split(/[,，\n]/).map(v=>v.trim()).filter(Boolean),cities:cities.split(/[,，\n]/).map(c=>c.trim()).filter(Boolean)};const r=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'configure',preferences:next})});const body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error);await onRefresh();setStep(2);toast.success('个人设置已保存');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="welcome-dialog"><DialogHeader><DialogTitle>配置你的 ApplyDesk</DialogTitle><DialogDescription>选择自己的求职范围，再让 Codex 连接浏览器检查。不需要飞书或模型 API Key。</DialogDescription></DialogHeader><div className="setup-steps">{['1 选择岗位','2 选择公司','3 连接 Codex'].map((label,i)=><span className={i===step?'active':''} key={label}>{label}</span>)}</div>
 {step===0&&<div className="form-grid"><label className="field span-all">工作城市<input autoFocus value={cities} placeholder="例如 北京；多个城市用逗号分隔" onChange={e=>setCities(e.target.value)}/></label><label className="field span-all">招聘类型<Select value={p.employment} onValueChange={v=>setP({...p,employment:v as Preferences['employment']})}><SelectTrigger aria-label="首次配置招聘类型"><SelectValue/></SelectTrigger><SelectContent>{RECRUITMENT_TYPES.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></label><label className="field span-all">目标岗位／关键词<textarea rows={3} value={targets} onChange={e=>setTargets(e.target.value)} placeholder="例如：法务，产品经理，物探数据解释"/></label><p className="fine span-all">不限行业，按自己的岗位名称或关键词填写。多个词用逗号或换行分隔。</p><Button className="span-all" disabled={!cities.trim()||!targets.trim()} onClick={()=>setStep(1)}>下一步：选择公司</Button></div>}
 {step===1&&<><p className="fine">先选少量公司验证。只有你勾选“我投过”的公司才读取个人投递进度。</p><div className="onboard-companies">{p.companies.map((c,i)=><div className="onboard-company" key={c.name}><label className="check-label"><input type="checkbox" checked={c.enabled} onChange={e=>setP({...p,companies:p.companies.map((v,j)=>j===i?{...v,enabled:e.target.checked,trackApplications:e.target.checked&&v.trackApplications}:v)})}/>{c.name}</label><label className="check-label"><input type="checkbox" disabled={!c.enabled} checked={c.trackApplications} onChange={e=>setP({...p,companies:p.companies.map((v,j)=>j===i?{...v,trackApplications:e.target.checked}:v)})}/>我投过</label></div>)}</div><p className="fine">默认每周检索。进入工作台后可添加其他公司、调整周期和关键词。</p><div className="actions"><Button variant="ghost" onClick={()=>setStep(0)}>上一步</Button><Button disabled={saving||!p.companies.some(c=>c.enabled)} onClick={()=>void save()}>{saving?'正在保存…':'保存并连接 Codex'}</Button></div></>}
 {step===2&&<><CodexActions data={data} onRefresh={onRefresh}/><div className="actions"><Button variant="ghost" onClick={()=>setStep(0)}>修改配置</Button><Button onClick={()=>onOpenChange(false)}>进入工作台</Button></div></>}
 </DialogContent></Dialog>;
}
