'use client';
import {useState} from 'react';
import {Button} from './ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from './ui/select';
import {toast} from 'sonner';
import type {Preferences} from '@/lib/preferences';
function Choice({value,options,onChange,label}:{value:string;options:string[];onChange:(v:string)=>void;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>;}
const split=(s:string)=>[...new Set(s.split(/[,，\n]/).map(s=>s.trim()).filter(Boolean))];
export default function PreferencesPanel({initial,onSaved}:{initial:Preferences;onSaved:()=>Promise<void>}){
 const [p,setP]=useState<Preferences>(()=>structuredClone(initial)),[cities,setCities]=useState(initial.cities.join('，')),[include,setInclude]=useState(initial.includeKeywords.join('，')),[exclude,setExclude]=useState(initial.excludeKeywords.join('，')),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false);
 const change=(next:Preferences)=>{setP(next);setDirty(true);};
 const updateCompany=(index:number,next:Partial<Preferences['companies'][number]>)=>change({...p,companies:p.companies.map((c,i)=>i===index?{...c,...next}:c)});
 const save=async()=>{setSaving(true);try{const response=await fetch('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,cities:split(cities),includeKeywords:split(include),excludeKeywords:split(exclude)})});const result=await response.json() as Preferences & {error?:string};if(!response.ok)throw new Error(result.error);setP(result);setDirty(false);await onSaved();toast.success('设置已保存，候选岗位已重新筛选');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}};
 return <div className="preferences-editor"><Tabs defaultValue="filters"><TabsList><TabsTrigger value="filters">岗位筛选</TabsTrigger><TabsTrigger value="companies">公司管理 · {p.companies.length}</TabsTrigger><TabsTrigger value="updates">自动更新</TabsTrigger></TabsList>
 <TabsContent value="filters"><div className="form-grid"><label className="field span-all">目标城市<input value={cities} onChange={e=>{setCities(e.target.value);setDirty(true);}} placeholder="北京；多个城市用逗号分隔"/></label><label className="field span-all">实习类型<Choice label="实习类型" value={p.employment} options={['日常实习','全部实习']} onChange={v=>change({...p,employment:v as Preferences['employment']})}/></label><fieldset className="span-all"><legend>岗位方向（至少选择一项）</legend><div className="actions wrap">{['大模型应用算法','Agent','业务算法','后训练'].map(d=><label className="check-label" key={d}><input type="checkbox" checked={p.directions.includes(d as Preferences['directions'][number])} onChange={e=>change({...p,directions:(e.target.checked?[...p.directions,d]:p.directions.filter(x=>x!==d)) as Preferences['directions']})}/>{d}</label>)}</div></fieldset><label className="field span-all">包含关键词（任意命中；留空不限制）<input value={include} onChange={e=>{setInclude(e.target.value);setDirty(true);}} placeholder="例如 RAG，SFT，推荐算法"/></label><label className="field span-all">排除关键词（任意命中即排除）<input value={exclude} onChange={e=>{setExclude(e.target.value);setDirty(true);}} placeholder="例如 产品经理，销售"/></label><p className="fine span-all">多个关键词用逗号分隔。缺少城市、实习类型或算法职责的岗位进入待核对。保存后立即重新筛选候选岗位，保留已投记录和“不考虑”决定。</p></div></TabsContent>
 <TabsContent value="companies"><p className="fine">启用的公司按所选频率检索岗位；勾选投递跟踪后，工作日每天检查个人投递。移除公司会保留历史记录。</p><div className="company-editor-list">{p.companies.map((c,i)=><section className="company-editor" key={i}><div className="company-editor-head"><input aria-label={`公司名称 ${i+1}`} value={c.name} onChange={e=>updateCompany(i,{name:e.target.value})} placeholder="公司名称"/><label className="check-label"><input type="checkbox" checked={c.enabled} onChange={e=>updateCompany(i,{enabled:e.target.checked})}/>启用</label><Button size="sm" variant="ghost" onClick={()=>change({...p,companies:p.companies.filter((_,j)=>j!==i)})}>移除</Button></div><label className="field">招聘官网<input type="url" value={c.url} onChange={e=>updateCompany(i,{url:e.target.value})} placeholder="https://招聘官网/职位列表"/></label><div className="company-editor-head"><Choice label={`${c.name||'新公司'}检索频率`} value={c.searchEveryDays===14?'每两周':'每周'} options={['每周','每两周']} onChange={v=>updateCompany(i,{searchEveryDays:v==='每两周'?14:7})}/><label className="check-label"><input type="checkbox" checked={c.trackApplications} onChange={e=>updateCompany(i,{trackApplications:e.target.checked})}/>跟踪投递进度</label></div>{c.trackApplications&&<label className="field">投递记录页（选填）<input type="url" value={c.applicationUrl} onChange={e=>updateCompany(i,{applicationUrl:e.target.value})} placeholder="不填则从官网进入个人中心"/></label>}</section>)}</div><Button variant="outline" onClick={()=>change({...p,companies:[...p.companies,{name:'',url:'',applicationUrl:'',enabled:true,trackApplications:false,searchEveryDays:7}]})}>添加公司</Button></TabsContent>
 <TabsContent value="updates"><label className="check-label"><input type="checkbox" checked={p.updatesEnabled} onChange={e=>change({...p,updatesEnabled:e.target.checked})}/>允许自动更新</label><p>工作日 10:00 · 北京时间</p><p className="fine">投递进度每天检查；新岗位只在该公司的每周或每两周周期到期时检索。首次未检索或上次检查失败的公司，会在下一次运行检查。</p><p className="fine">执行器使用本机 Codex 和已连接的 Edge。电脑须开机联网、Codex 保持运行、Edge 浏览器连接可用。登录过期会显示在官网接入中；不会把登录失败判为拒绝。</p><p className="fine">开关控制每次任务是否执行；实际定时任务的绑定状态与运行结果显示在工作台。其他人克隆项目后，需按项目文档绑定自己的定时任务。</p></TabsContent></Tabs><div className="preferences-actions"><span className="fine">{dirty?'有未保存的修改':'设置已保存'}</span><Button disabled={saving||!dirty} onClick={()=>void save()}>{saving?'正在保存…':'保存设置'}</Button></div></div>;
}
